import axios from 'axios'

export async function getUsers() {
  const response = await axios.get<User[]>(
    'https://jsonplaceholder.typicode.com/users'
  )
  return response.data
}

export async function getUser(id: number) {
  const response = await axios.get<User>(
    `https://jsonplaceholder.typicode.com/users/${id}`
  )
  return response.data
}

// Generated by https://quicktype.io

export interface User {
  id: number
  name: string
  username: string
  email: string
  address: Address
  phone: string
  website: string
  company: Company
}

export interface Address {
  street: string
  suite: string
  city: string
  zipcode: string
  geo: Geo
}

export interface Geo {
  lat: string
  lng: string
}

export interface Company {
  name: string
  catchPhrase: string
  bs: string
}
